---
dist: xenial  # required for Python >= 3.7 (travis-ci/travis-ci#9069)
language: python
python:
  - 3.7
install:
  - pip install -qq yamllint==1.8.1
script:
  - yamllint --strict $(git ls-files '*.yaml' '*.yml')
